[package]
name = "fox_game"
authors = ["qiwihui"]
version = "0.0.1"
# published-at = ""

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
# SmartInscription = { git = "https://github.com/movescriptions/movescriptions.git", subdir = "sui", rev = "main"}
SmartInscription = { local = "../movescriptions/sui" }

[addresses]
fox_game = "0x0"
# smartinscription = "0x51876533be1dfb70d54d5049bf373e7c4ee204da124dd5b2688cd497c8aceb61"
