name: Set time to Sui Wolf Game on a CRON Schedule

on:
  push:
  schedule:
    # Runs "At every 15th minute" (see https://crontab.guru)
    - cron: '*/15 * * * *'
jobs:
  build:
    name: Trigger setting time
    runs-on: ubuntu-latest
    steps:
      - name: install sui
        run: curl -L https://github.com/MystenLabs/sui/releases/download/devnet-0.23.0/sui > sui
      - run: chmod +x sui
      - name: import address
        run: ./sui keytool import "${{ secrets.MNEMONIC }}" ed25519
      - name: switch address
        run: |
          (sleep 1; echo y;sleep 1;echo;sleep 1;echo 0;) | ./sui client switch --address 0xa3e46ec682bb5082849c240d2f2d20b0f6e054aa
          ./sui client switch --address 0xa3e46ec682bb5082849c240d2f2d20b0f6e054aa
      - name: call set timer
        run: ./sui client call --function set_timestamp --module fox --package 0x947542974992e28319e2a91ece12d609c53b9675 --args 0xb3feb0f580b314e630293fa1c78cc49bd343f94b 0xef7ab8315143e54a83906b74e347da80dff63379 \"$(date +%s)\" --gas-budget 30000
