name: Set time to Sui Wolf Game on a CRON Schedule

on:
  push:
  schedule:
    # Runs "At every 15th minute" (see https://crontab.guru)
    - cron: '*/15 * * * *'
jobs:
  build:
    name: Trigger setting time
    runs-on: ubuntu-latest
    steps:
      - name: install sui
        run: curl -L https://github.com/MystenLabs/sui/releases/download/devnet-0.21.0/sui > sui
      - run: chmod +x sui
      - name: import address
        run: ./sui keytool import "${{ secrets.MNEMONIC }}" ed25519
      - name: switch address
        run: |
          (sleep 1; echo y;sleep 1;echo;sleep 1;echo 0;) | ./sui client switch --address 0xa3e46ec682bb5082849c240d2f2d20b0f6e054aa
          ./sui client switch --address 0xa3e46ec682bb5082849c240d2f2d20b0f6e054aa
      - name: call set timer
        run: ./sui client call --function set_timestamp --module fox --package 0x54b399071e3902b7f832695c4e0c5093b3adf1ec --args 0xbb1dcd2515748ca8d1727dcd3253cd142236da7e 0xa366a7aff2a4eee1a59b362707ce25e6f760d7f9 \"$(date +%s)\" --gas-budget 30000
