name: Set time to Sui Wolf Game on a CRON Schedule

on:
  push:
  schedule:
    # Runs "At every 2nd minute" (see https://crontab.guru)
    - cron: '0 * * * *'
jobs:
  build:
    name: Trigger setting time
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: sudo apt-get install -y libssl-dev libclang-dev
      - name: install sui
        run: cargo install --locked --git https://github.com/MystenLabs/sui.git --branch devnet sui
      - run: source "$HOME/.cargo/env"
      - name: import address
        run: sui keytool import "${{ secrets.MNEMONIC }}" ed25519
      - name: switch address
        run: sui client switch --address 0xa3e46ec682bb5082849c240d2f2d20b0f6e054aa
      - name: call set timer
        run: sui client call --function set_timestamp --module fox --package 0xa12db00ce4eb63ffa28fb384a4119e10fb688651 --args 0xdffbff81a48aa3cd9d24d9501ad552923218bfe0 0x741cdbe1fabfcb51e2e6c03b8b1823503d46eaf1 \"$(date +%s)\" --gas-budget 30000
